version: '3.8'

services:
  backend:
    container_name: ginnovation-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://admin:secret@mongo:27017
      - MongoDB__Database=GinnovationServiceReportDB
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: ginnovation-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
